### ISSUE TITLE
Pull code from vyasr/cython-cmake/

### ISSUE THREAD

**Issue by vyasr** [scikit-build/cython-cmake#2]
@jcfr I've got the full package largely working in https://github.com/vyasr/cython-cmake/. I think we should either delete this repository and migrate that one into the scikit-build org, or force push all the changes from that repo to overwrite the code in this one. It looks like the only code in this repo at the moment is from some cookiecutter-like template, so either approach should be safe.

**Comment by vyasr** [comment]
There are still some significant changes that need to be made before my cython-cmake is ready for a release, but they're mostly around things like CI or Windows support and would be better handled in a shared repository rather than one that I own.

**Comment by jcfr** [comment]
Thanks for consolidating your work into the `cython-cmake` repository :pray:
This will be helpful :rocket:

**Comment by jcfr** [comment]
History associated with the files `FindCython.cmake` and `UseCython.cmake` from the repositories `thewtex/cython-cmake-example`[^1] and `scikit-build/scikit-build`[^2] has been extracted and integrated into this project.

[^1]: https://github.com/thewtex/cython-cmake-example/tree/master/cmake
[^2]: https://github.com/scikit-build/scikit-build/tree/main/skbuild/resources/cmake

Then, relevant updates from `vyasr/cython-cmake` have been adapted.

The modernized function is called `Cython_compile_pyx` and it internally passes the `-M`[^3] flag to cython as well as the corresponding custom command parameter called `DEPFILE`[^4].

The CMake modules are distributed in the `cython-cmake` wheel. See https://pypi.org/project/cython-cmake/

[^3]: https://cython.readthedocs.io/en/latest/src/changes.html#build-integration
[^4]: https://cmake.org/cmake/help/latest/command/add_custom_command.html

```
#   Cython_compile_pyx(<pyx_file1> [<pyx_file2> ...]
#                     [TARGET_LANGUAGE C | CXX]
#                     [LANGUAGE_LEVEL 2 | 3 | 3str]
#                     [OUTPUT_VAR <OutputVar>])
```

**Comment by jcfr** [comment]
The `core-cython-hello` sample project has also been updated to use the `Cython_compile_pyx` function. See https://github.com/scikit-build/scikit-build-sample-projects/pull/43
