### ISSUE TITLE
Fedora packaging

### ISSUE THREAD

**Issue by LecrisUT** [scikit-build/cython-cmake#47]
Let me know when I should start packaging this project.

**Comment by henryiii** [comment]
Probably after #32 is in and we make a release?

**Comment by henryiii** [comment]
v0.2.0 is out.

**Comment by LecrisUT** [comment]
Are the `UseCython.cmake` files effectively vendored or would they be forked? If the latter could you change the copyright notice for it to reflect that?

**Comment by henryiii** [comment]
If someone uses this package, they would use the files from the package. If they prefer, they can vendor the files, which means they don't need to get this package from Fedora. What change were you thinking of?

**Comment by LecrisUT** [comment]
I was thinking about the more general case:
https://github.com/scikit-build/cython-cmake/blob/ec03867a41ded0a91d1b22e51f659a480d9a3da8/src/cython_cmake/cmake/UseCython.cmake#L58

If the file is being maintained externally than I would need to add a `Bundles` to show that, otherwise it would be fine as-is

**Comment by henryiii** [comment]
I think that date was inherited. @jcfr?

**Comment by LecrisUT** [comment]
Was thinking you could just add
```
# Copyright 202x Scikit-build developers
```
Or equivalent, marking when it got forked from kitware's

**Comment by henryiii** [comment]
I don't think it's a good idea to assign copyright to something that's not a legal entity. A person works, or a company, but "... developers" is too fuzzy and unclear. That's what I remember from a discussion with a lawyer a long time ago, I might be misremembering it though.

**Comment by LecrisUT** [comment]
I remember there being some discussion on Fedora mail list[^1] about jaraco removing copyright notice[^2]. I need to read through the mail list more carefully, but afaiu it is ok if the authorship is self contained. There is also [this article](https://www.linuxfoundation.org/blog/blog/copyright-notices-in-open-source-software-projects) which many people resonate with, but of course inal.

[^1]: https://lists.fedoraproject.org/archives/list/legal@lists.fedoraproject.org/thread/FOS55EPT4MEJXIY3CHWM26X5ACG66TQU/
[^2]: https://github.com/jaraco/skeleton/issues/78
